LOCAL_PATH := $(call my-dir)

FFMPEG_CFLAGS := \
    -DAMFFMPEG \
    -DHAVE_AV_CONFIG_H \
    -I$(LOCAL_PATH) \
    -Wno-error=return-type \
    -Wno-missing-field-initializers \
    -Wno-parentheses \
    -Wno-pointer-sign \
    -Wno-sign-compare \
    -Wno-switch \
    -Wno-string-plus-int \
    -Wno-implicit-function-declaration \
    -fPIC \

FFMPEG_LDFLAGS := -Wl,--as-needed -Wl,-Bsymbolic -lm

$(warning "Define TARGET_ARCH: " $(TARGET_ARCH))

ifeq ($(TARGET_ARCH),$(filter $(TARGET_ARCH),arm arm64))
# Generated by configure. Should match the list of source files in

FFMPEG_CFLAGS += \
    -std=c99 -llvm -DDISABLE_NEONINTR \
    -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
    -D_ISOC99_SOURCE -D_POSIX_C_SOURCE=200112 \
    ${FFMPEG_CFLAGS_$(TARGET_ARCH_VARIANT)}
endif

LOCAL_CLANG := false


FFMPEG_SOURCE_ARM := $(shell cat $(LOCAL_PATH)/"ffmpeg.arm.src")

#$(warning "Define FFMPEG_SOURCE_ARM: " $(FFMPEG_SOURCE_ARM))

FFMPEG_SOURCE_ARM64 := $(shell cat $(LOCAL_PATH)/"ffmpeg.arm64.src")

#$(warning "Define FFMPEG_SOURCE_ARM64: " $(FFMPEG_SOURCE_ARM64))


GIT_VERSION="$(shell cd $(LOCAL_PATH);git log | grep commit -m 1 | cut -d' ' -f 2)"
GIT_VERSION_SHORT="$(shell  cd $(LOCAL_PATH);git rev-parse --short $(GIT_VERSION) | sed -e 's/^ *//g')"
VERSION_MAJOR="$(shell  cd $(LOCAL_PATH);grep major version.json |cut -d : -f 2 |cut -d , -f 1 | sed -e 's/^ *//g')"
AMLOGIC_FFMPEG_VER="$(shell cd $(LOCAL_PATH);grep amlogicver version.json |cut -d : -f 2 |cut -d , -f 1 | sed -e 's/^ *//g')"
VERSION_MINOR="$(shell  cd $(LOCAL_PATH);grep minor version.json |cut -d : -f 2 |cut -d , -f 1 | sed -e 's/^ *//g')"
CURR_VER_BASE_COMMIT="$(shell  cd $(LOCAL_PATH);grep commit version.json |cut -d : -f 2 |cut -d , -f 1 | sed -e 's/^ *//g')"
CURR_VER_COMMITS_COUNT="$(shell  cd $(LOCAL_PATH);git rev-list --first-parent --abbrev-commit --pretty=oneline $(CURR_VER_BASE_COMMIT)^..HEAD |wc -l | sed -e 's/^ *//g')"
VERSION_STRING=V$(VERSION_MAJOR).$(VERSION_MINOR).$(AMLOGIC_FFMPEG_VER).$(CURR_VER_COMMITS_COUNT)-g$(GIT_VERSION_SHORT)
FFMPEG_CFLAGS += -DFF_VERSION_STRING=\"${VERSION_STRING}\"
$(warning "Define VERSION_STRING: " $(VERSION_STRING))

include $(CLEAR_VARS)
LOCAL_MODULE := libamffmpeg
LOCAL_LICENSE_KINDS := SPDX-license-identifier-Apache-2.0 SPDX-license-identifier-GPL-1.0+ SPDX-license-identifier-GPL-2.0+ SPDX-license-identifier-LGPL-2.0+ SPDX-license-identifier-MIT SPDX-license-identifier-ISC SPDX-license-identifier-BSD SPDX-license-identifier-LGPL-2.1+ legacy_proprietary
LOCAL_LICENSE_CONDITIONS := notice

LOCAL_SYSTEM_EXT_MODULE := true
LOCAL_MODULE_TAGS := optional

ifeq ($(TARGET_ARCH),$(filter $(TARGET_ARCH),arm arm64))
LOCAL_ARM_MODE := arm
endif

LOCAL_CFLAGS := $(FFMPEG_CFLAGS) -DFF_API_AV_GETTIME=0

LOCAL_CFLAGS_32 := -DARCH_ARM
LOCAL_CFLAGS_64 := -DARCH_AARCH64

LOCAL_LDFLAGS += $(FFMPEG_LDFLAGS)

LOCAL_LDFLAGS_arm := -Wl
LOCAL_LDFLAGS_arm64 := -Wl


LOCAL_SRC_FILES_arm := $(FFMPEG_SOURCE_ARM)

LOCAL_SRC_FILES_arm64 := $(FFMPEG_SOURCE_ARM64)

LOCAL_C_INCLUDES += external/zlib
LOCAL_C_INCLUDES += external/libxml2/include

LOCAL_C_INCLUDES += external/boringssl/src/include
LOCAL_SHARED_LIBRARIES := libutils liblog libdl libz libcutils
LOCAL_SHARED_LIBRARIES += libssl libcrypto
LOCAL_SHARED_LIBRARIES += libxml2

include $(BUILD_SHARED_LIBRARY)



ifneq (0, $(shell expr $(PLATFORM_VERSION) \>= 9))
include $(CLEAR_VARS)

LOCAL_MODULE := libamffmpeg.vendor
LOCAL_LICENSE_KINDS := SPDX-license-identifier-Apache-2.0 SPDX-license-identifier-GPL-1.0+ SPDX-license-identifier-GPL-2.0+ SPDX-license-identifier-LGPL-2.0+ SPDX-license-identifier-MIT SPDX-license-identifier-ISC SPDX-license-identifier-BSD SPDX-license-identifier-LGPL-2.1+ legacy_proprietary
LOCAL_LICENSE_CONDITIONS := notice

LOCAL_VENDOR_MODULE := true

LOCAL_MODULE_TAGS := optional

ifeq ($(TARGET_ARCH),$(filter $(TARGET_ARCH),arm arm64))
LOCAL_ARM_MODE := arm
endif

LOCAL_CFLAGS := $(FFMPEG_CFLAGS) -DFF_API_AV_GETTIME=0

#LOCAL_CFLAGS_arm := $(FFMPEG_CFLAGS_armv7-a-neon)

LOCAL_CFLAGS_32 := -DARCH_ARM
LOCAL_CFLAGS_64 := -DARCH_AARCH64

LOCAL_LDFLAGS += $(FFMPEG_LDFLAGS)

LOCAL_LDFLAGS_arm := -Wl
LOCAL_LDFLAGS_arm64 := -Wl

#LOCAL_SRC_FILES :=

LOCAL_SRC_FILES_arm := $(FFMPEG_SOURCE_ARM)

LOCAL_SRC_FILES_arm64 := $(FFMPEG_SOURCE_ARM64)

LOCAL_C_INCLUDES += external/zlib
LOCAL_C_INCLUDES += external/libxml2/include

LOCAL_C_INCLUDES += external/boringssl/src/include
LOCAL_SHARED_LIBRARIES := libutils liblog libdl libz libcutils
LOCAL_SHARED_LIBRARIES += libxml2

LOCAL_SHARED_LIBRARIES += libssl libcrypto
include $(BUILD_SHARED_LIBRARY)
endif
