/* Automatically generated by configure - do not modify! */
#ifndef __FFMPEG_CONFIG_H
#define __FFMPEG_CONFIG_H

#ifdef __aarch64__
#pragma message("__aarch64__ cpu type.")
#endif
#ifdef __arm__
#pragma message("__arm__ cpu type.")
#endif


#ifdef __aarch64__
#include "config.arm64.h"
#pragma message("__aarch64__ cpu type. config.arm64.h")
#elif defined __arm__
#include "config.arm.h"
#pragma message("__arm__ cpu type. config.arm.h")
#else
#pragma message("unknown cpu type.")
#endif
#endif /* __FFMPEG_CONFIG_H */
